from enum import StrEnum


class Decision(StrEnum):
    ALLOW = "ALLOW"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"
    DENY = "DENY"
    QUARANTINE = "QUARANTINE"
    SUSPEND = "SUSPEND"


class WorkflowStage(StrEnum):
    RECEIVED = "RECEIVED"
    IDENTITY_VALIDATED = "IDENTITY_VALIDATED"
    AUTHORITY_VALIDATED = "AUTHORITY_VALIDATED"
    DATA_PROFILED = "DATA_PROFILED"
    CLASSIFIED = "CLASSIFIED"
    PLAN_AUTHORIZED = "PLAN_AUTHORIZED"
    GENERATED = "GENERATED"
    EVALUATED = "EVALUATED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    RELEASED = "RELEASED"
    DENIED = "DENIED"
    QUARANTINED = "QUARANTINED"
    SUSPENDED = "SUSPENDED"


class FieldClass(StrEnum):
    DIRECT_IDENTIFIER = "DIRECT_IDENTIFIER"
    QUASI_IDENTIFIER = "QUASI_IDENTIFIER"
    SENSITIVE_ATTRIBUTE = "SENSITIVE_ATTRIBUTE"
    OPERATIONAL_ATTRIBUTE = "OPERATIONAL_ATTRIBUTE"
    DERIVED_FEATURE = "DERIVED_FEATURE"


class ReleaseDisposition(StrEnum):
    PERMITTED = "RELEASE_PERMITTED"
    PROHIBITED = "RELEASE_PROHIBITED"


class ApprovalRole(StrEnum):
    DATA_OWNER = "DATA_OWNER"
    PRIVACY_OFFICER = "PRIVACY_OFFICER"


class ApprovalOutcome(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"


class Scenario(StrEnum):
    INTERNAL_ALLOW = "internal_allow"
    EXTERNAL_APPROVAL = "external_approval"
    PRIVACY_LEAKAGE = "privacy_leakage"
    PROMPT_INJECTION = "prompt_injection"
